git:
  depth: 10
language: ruby

rvm: 2.0.0

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script:
  - cd dashboard
  - bundle exec rake -t db:create db:schema:load

script: bundle exec rake -t

env:
  - DB=mysql

