git:
  depth: 10
language: ruby

rvm: 2.0.0

sudo: false

cache: bundler

gemfile: Gemfile

bundler_args: --without development --deployment

before_script: "echo npm_use_sudo: false >> locals.yml"

script: "bundle exec rake -t travis:$TEST_TASK"

env:
  - DB=mysql TEST_TASK=lint
  - DB=mysql TEST_TASK=dashboard
  - DB=mysql TEST_TASK=pegasus
  - DB=mysql TEST_TASK=apps
  - DB=mysql TEST_TASK=blockly_core

