# Docker Compose file for running the site locally.
#
# Set the FIXUID and FIXGID env variables with these commands (or put them in your .bash_profile / .bashrc):
# export FIXUID=$(id -u)
# export FIXGID=$(id -g)
#
# then run:
# docker-compose -f unit-tests-compose.yml up
#
# To clean up:
# docker-compose -f unit-tests-compose.yml down

version: "3"
services:
  site:
    image: codedotorg/code-dot-org:add-git-lfs
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ../:/home/circleci/code-dot-org:delegated
      - rbenv:/home/circleci/.rbenv
      - mysqldata:/var/lib/mysql
      - yarncache:/home/circleci/.cache
      - gcloud_config:/home/circleci/.config/gcloud
      - $HOME/.aws:/home/circleci/.aws
    tty: true
    stdin_open: true
    environment:
      - AWS_PROFILE
    command: bash -c "docker/dev_setup.sh"

volumes:
  mysqldata:
  rbenv:
  yarncache:
  gcloud_config:
