# Docker Compose file for running ui tests.
#
# To run, set the following env variables (values obtainable from Circle):
# PROPERTIES_ENCRYPTION_KEY
# CLOUDFRONT_KEY_PAIR_ID
# CLOUDFRONT_PRIVATE_KEY
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# APPLITOOLS_KEY
# FIREBASE_NAME
# FIREBASE_SECRET
# SAUCE_USERNAME
# SAUCE_ACCESS_KEY
#
# Also set the FIXUID and FIXGID env variables with these commands (or put them in your .bash_profile / .bashrc):
# export FIXUID=$(id -u)
# export FIXGID=$(id -g)
#
# then run:
# docker-compose -f ui-tests-compose.yml up
# 
# To clean up:
# docker-compose -f ui-tests-compose.yml down

version: '3'
services:
  site:
    image: wintercdo/code-dot-org:0.7
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ../:/home/circleci/code-dot-org:delegated
      - nodemodules:/home/circleci/code-dot-org/apps/node_modules
      - rbenv:/home/circleci/.rbenv
      - mysqldata:/var/lib/mysql
      - yarncache:/home/circleci/.cache
    env_file:
      - env.list
    command: /bin/sh -c "docker/ui_tests.sh"

  ui-tests-redis:
    image: redis

volumes:
  nodemodules:
  mysqldata:
  rbenv:
  yarncache:
