apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashboard.fullname" . }}-locals
  labels:
    {{- include "dashboard.labels" . | nindent 4 }}
data:
  locals.yml: |

    db_writer: 'mysql://root@dashboard-db/'

    netsim_redis_groups:
    - master: redis://redis:6379

    # FIXME: do these default to these values already? remove if so
    dashboard_enable_pegasus: false
    build_apps: true
    use_my_apps: true