name: Run one test tests
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:        
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1   
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY:  ${{ secrets.SAUCE_ACCESS_KEY }}      
      LD_LIBRARY_PATH: "/usr/local/lib"
    steps:    
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3       
      - name: Get actions code
        uses: actions/checkout@v3    
        
      - name: Rake run integration tests
        run:  |
          echo "testing failure"  
          RUN locale-gen C.UTF-8 || true
          ENV LANG=C.UTF-8          
      - name: say-hello
        uses: ./.github/actions/start-server-job-actions  
      - name: Install mysql
        uses: ./.github/actions/install-mysql                    
      - name: Install test variables
        uses: ./.github/actions/install-test-variables            
      - name: Install Ruby
        uses: ./.github/actions/install-ruby
      - name: Install apt packages
        uses: ./.github/actions/install-apt-packages
      - name: Install node
        uses: ./.github/actions/install-node        
      - name: Install rake dependencies 
        uses: ./.github/actions/install-rake-dependencies
      - name: Rake run integration tests
        run:  |
          echo "testing failure"  
          bundle exec rake test:changed --trace
        continue-on-error: true       
 
