name: Run UI tests composite actions
on:
  workflow_dispatch:
jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      RACK_ENV: test
      DISABLE_SPRING: 1
    steps:
      - name: Get actions code
        uses: actions/checkout@v3
      - name: say-hello
        uses: ./.github/actions/start-job-check
      - name: Install mysql
        uses: ./.github/actions/install-mysql
      - name: Install test variables
        uses: ./.github/actions/test-variables-installer
      - name: Install Ruby
        uses: ./.github/actions/install-ruby
      - name: Install apt packages
        uses: ./.github/actions/install-apt-packages
      - name: Install node
        uses: ./.github/actions/install-node
      - name: Install rake
        uses: ./.github/actions/install-rake-dependencies
